// <auto-generated />
using System;
using CloneWhatsApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloneWhatsApp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230222710_AddSilenciarArchivarChat")]
    partial class AddSilenciarArchivarChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CloneWhatsApp.API.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescripcionGrupo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenGrupo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombreGrupo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.ChatParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<bool>("Silenciado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("SilenciadoHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UltimaLectura")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ChatId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ChatParticipantes");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ContactoUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombrePersonalizado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoUsuarioId");

                    b.HasIndex("UsuarioId", "ContactoUsuarioId")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ColorFondo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Contenido")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FechaExpiracion");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.EstadoMensajeUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEstado")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MensajeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("MensajeId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EstadosMensaje");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Llamada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LlamadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("LlamadorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Contenido")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<bool>("Editado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EliminadoParaTodos")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MensajeRespondidoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RemitenteId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("TamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("FechaEnvio");

                    b.HasIndex("MensajeRespondidoId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EstaEnLinea")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaConexion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroTelefono")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.VistaEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaVista")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstadoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("VistasEstados");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.ChatParticipante", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Chat", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Usuario")
                        .WithMany("ChatsParticipante")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Contacto", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "ContactoUsuario")
                        .WithMany("ContactoDe")
                        .HasForeignKey("ContactoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Usuario")
                        .WithMany("Contactos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Estado", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Usuario")
                        .WithMany("Estados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.EstadoMensajeUsuario", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Mensaje", "Mensaje")
                        .WithMany("Estados")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Llamada", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Llamador")
                        .WithMany()
                        .HasForeignKey("LlamadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Llamador");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Mensaje", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Mensaje", "MensajeRespondido")
                        .WithMany()
                        .HasForeignKey("MensajeRespondidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Remitente")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("MensajeRespondido");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.VistaEstado", b =>
                {
                    b.HasOne("CloneWhatsApp.API.Models.Estado", "Estado")
                        .WithMany("Vistas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneWhatsApp.API.Models.Usuario", "Usuario")
                        .WithMany("VistasEstados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Chat", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Estado", b =>
                {
                    b.Navigation("Vistas");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Mensaje", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("CloneWhatsApp.API.Models.Usuario", b =>
                {
                    b.Navigation("ChatsParticipante");

                    b.Navigation("ContactoDe");

                    b.Navigation("Contactos");

                    b.Navigation("Estados");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("VistasEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
